# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uemac', models.CharField(max_length=100)),
                ('timestamp', models.FloatField(blank=True, default=None, null=True)),
                ('signal', models.IntegerField(blank=True, default=None, null=True)),
                ('noise', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
